import { Song } from '@/contexts/KaraokeContext'

export const songDatabase: Song[] = [
  {
    id: '1',
    title: 'Recairei',
    artist: 'Barões da Pisadinha',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 180,
    category: 'Piseiro',
    language: 'Portuguese',
  },
  {
    id: '2',
    title: 'Tá Rocheda',
    artist: 'Barões da Pisadinha',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 165,
    category: 'Piseiro',
    language: 'Portuguese',
  },
  {
    id: '3',
    title: 'Deixa Tudo Como Tá',
    artist: 'Barões da Pisadinha',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 175,
    category: 'Piseiro',
    language: 'Portuguese',
  },
  {
    id: '4',
    title: 'Batom de Cereja',
    artist: 'Israel & Rodolffo',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 195,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '5',
    title: 'Jenifer',
    artist: 'Gabriel Diniz',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 210,
    category: 'Forró',
    language: 'Portuguese',
  },
  {
    id: '6',
    title: 'Morena',
    artist: 'Luan Santana',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 220,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '7',
    title: 'Largadinho',
    artist: 'Claudia Leitte',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 185,
    category: 'Axé',
    language: 'Portuguese',
  },
  {
    id: '8',
    title: 'Coração Radiante',
    artist: 'Marília Mendonça',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 240,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '9',
    title: 'Evidências',
    artist: 'Chitãozinho & Xororó',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 280,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '10',
    title: 'Lepo Lepo',
    artist: 'Psirico',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 195,
    category: 'Axé',
    language: 'Portuguese',
  },
  {
    id: '11',
    title: 'Dança Kuduro',
    artist: 'Lucenzo feat. Big Ali',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 205,
    category: 'Funk',
    language: 'Portuguese',
  },
  {
    id: '12',
    title: 'Envolvimento',
    artist: 'MC Loma',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 150,
    category: 'Funk',
    language: 'Portuguese',
  },
  {
    id: '13',
    title: 'Beat da Gaiola',
    artist: 'Dennis DJ',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 170,
    category: 'Funk',
    language: 'Portuguese',
  },
  {
    id: '14',
    title: 'Calma',
    artist: 'Pedro Capó & Farruko',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 250,
    category: 'Pop Latino',
    language: 'Portuguese',
  },
  {
    id: '15',
    title: 'Bebi Liguei',
    artist: 'Marília Mendonça',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 215,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '16',
    title: 'Esqueça-me Se For Capaz',
    artist: 'Marília Mendonça',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 230,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '17',
    title: 'Deu Onda',
    artist: 'MC G15',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 160,
    category: 'Funk',
    language: 'Portuguese',
  },
  {
    id: '18',
    title: 'Ragatanga',
    artist: 'Rouge',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 200,
    category: 'Pop',
    language: 'Portuguese',
  },
  {
    id: '19',
    title: 'Melhor Eu Ir',
    artist: 'Péricles',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 245,
    category: 'Pagode',
    language: 'Portuguese',
  },
  {
    id: '20',
    title: 'Sou Ou Não Sou',
    artist: 'Thiaguinho',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 220,
    category: 'Pagode',
    language: 'Portuguese',
  },
  {
    id: '21',
    title: 'Pra Sempre Pobre',
    artist: 'Gusttavo Lima',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 240,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '22',
    title: 'Apelido Carinhoso',
    artist: 'Gusttavo Lima',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 225,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '23',
    title: 'Ficha Limpa',
    artist: 'Gusttavo Lima',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 235,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '24',
    title: 'Onda Diferente',
    artist: 'Anitta, Ludmilla, Snoop Dogg',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    duration: 215,
    category: 'Funk',
    language: 'Portuguese',
  },
]

export function searchSongs(query: string): Song[] {
  if (!query.trim()) return songDatabase
  
  const lowerQuery = query.toLowerCase()
  return songDatabase.filter(
    song =>
      song.title.toLowerCase().includes(lowerQuery) ||
      song.artist.toLowerCase().includes(lowerQuery)
  )
}

export function getSongsByCategory(category: string): Song[] {
  return songDatabase.filter(song => song.category === category)
}

export const categories = [
  'Piseiro',
  'Sertanejo',
  'Funk',
  'Forró',
  'Axé',
  'Pagode',
  'Pop',
  'Pop Latino',
]
