import { Song } from '@/contexts/KaraokeContext'

export const songDatabase: Song[] = [
  {
    id: '1',
    title: 'Garota de Ipanema',
    artist: 'Tom Jobim',
    youtubeId: 'UJkxFhFRFDA',
    thumbnail: 'https://img.youtube.com/vi/UJkxFhFRFDA/maxresdefault.jpg',
    duration: 320,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '2',
    title: 'Evidências',
    artist: 'Chitãozinho & Xororó',
    youtubeId: 'oPQ3o14ksaM',
    thumbnail: 'https://img.youtube.com/vi/oPQ3o14ksaM/maxresdefault.jpg',
    duration: 280,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '3',
    title: 'Aquarela',
    artist: 'Toquinho',
    youtubeId: 'fNHqoJe2lDE',
    thumbnail: 'https://img.youtube.com/vi/fNHqoJe2lDE/maxresdefault.jpg',
    duration: 245,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '4',
    title: 'Asa Branca',
    artist: 'Luiz Gonzaga',
    youtubeId: 'CKjbVi7Jk_g',
    thumbnail: 'https://img.youtube.com/vi/CKjbVi7Jk_g/maxresdefault.jpg',
    duration: 200,
    category: 'Forró & Regional',
    language: 'Portuguese',
  },
  {
    id: '5',
    title: 'País Tropical',
    artist: 'Jorge Ben Jor',
    youtubeId: 'MCzqErq29Kw',
    thumbnail: 'https://img.youtube.com/vi/MCzqErq29Kw/maxresdefault.jpg',
    duration: 260,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '6',
    title: 'Chega de Saudade',
    artist: 'João Gilberto',
    youtubeId: 'cHxp-xcEKLI',
    thumbnail: 'https://img.youtube.com/vi/cHxp-xcEKLI/maxresdefault.jpg',
    duration: 200,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '7',
    title: 'Mas Que Nada',
    artist: 'Sérgio Mendes',
    youtubeId: 'FbSHFuUP9dY',
    thumbnail: 'https://img.youtube.com/vi/FbSHFuUP9dY/maxresdefault.jpg',
    duration: 195,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '8',
    title: 'Ai Se Eu Te Pego',
    artist: 'Michel Teló',
    youtubeId: 'hcm55lU9knw',
    thumbnail: 'https://img.youtube.com/vi/hcm55lU9knw/maxresdefault.jpg',
    duration: 185,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '9',
    title: 'Festa',
    artist: 'Ivete Sangalo',
    youtubeId: '_7Mk3Mh-7ME',
    thumbnail: 'https://img.youtube.com/vi/_7Mk3Mh-7ME/maxresdefault.jpg',
    duration: 230,
    category: 'Axé & Pop',
    language: 'Portuguese',
  },
  {
    id: '10',
    title: 'O Mundo é um Moinho',
    artist: 'Cartola',
    youtubeId: '2U_OeKCpmDI',
    thumbnail: 'https://img.youtube.com/vi/2U_OeKCpmDI/maxresdefault.jpg',
    duration: 190,
    category: 'Samba & Pagode',
    language: 'Portuguese',
  },
  {
    id: '11',
    title: 'Sozinho',
    artist: 'Caetano Veloso',
    youtubeId: 'pza3gT0ZQkc',
    thumbnail: 'https://img.youtube.com/vi/pza3gT0ZQkc/maxresdefault.jpg',
    duration: 220,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '12',
    title: 'Oceano',
    artist: 'Djavan',
    youtubeId: 'MnPJD8v2StI',
    thumbnail: 'https://img.youtube.com/vi/MnPJD8v2StI/maxresdefault.jpg',
    duration: 265,
    category: 'Bossa Nova & MPB',
    language: 'Portuguese',
  },
  {
    id: '13',
    title: 'Ela Partiu',
    artist: 'Tim Maia',
    youtubeId: 'S_lDxOb3PNM',
    thumbnail: 'https://img.youtube.com/vi/S_lDxOb3PNM/maxresdefault.jpg',
    duration: 240,
    category: 'Soul & Funk',
    language: 'Portuguese',
  },
  {
    id: '14',
    title: 'Que País é Este',
    artist: 'Legião Urbana',
    youtubeId: 'TnLVHKfPpyM',
    thumbnail: 'https://img.youtube.com/vi/TnLVHKfPpyM/maxresdefault.jpg',
    duration: 260,
    category: 'Rock Brasileiro',
    language: 'Portuguese',
  },
  {
    id: '15',
    title: 'Exagerado',
    artist: 'Cazuza',
    youtubeId: '9K2NnXOZ0iw',
    thumbnail: 'https://img.youtube.com/vi/9K2NnXOZ0iw/maxresdefault.jpg',
    duration: 245,
    category: 'Rock Brasileiro',
    language: 'Portuguese',
  },
  {
    id: '16',
    title: 'Eduardo e Mônica',
    artist: 'Legião Urbana',
    youtubeId: 'fZp9MpQmkzA',
    thumbnail: 'https://img.youtube.com/vi/fZp9MpQmkzA/maxresdefault.jpg',
    duration: 290,
    category: 'Rock Brasileiro',
    language: 'Portuguese',
  },
  {
    id: '17',
    title: 'Trem das Onze',
    artist: 'Adoniran Barbosa',
    youtubeId: 'VgS_-u4DK3M',
    thumbnail: 'https://img.youtube.com/vi/VgS_-u4DK3M/maxresdefault.jpg',
    duration: 210,
    category: 'Samba & Pagode',
    language: 'Portuguese',
  },
  {
    id: '18',
    title: 'De Janeiro a Janeiro',
    artist: 'Roberta Sá',
    youtubeId: 'UqXXz3MhQRA',
    thumbnail: 'https://img.youtube.com/vi/UqXXz3MhQRA/maxresdefault.jpg',
    duration: 235,
    category: 'Samba & Pagode',
    language: 'Portuguese',
  },
  {
    id: '19',
    title: 'Abertura',
    artist: 'Sandy & Junior',
    youtubeId: '_9R8makmf5U',
    thumbnail: 'https://img.youtube.com/vi/_9R8makmf5U/maxresdefault.jpg',
    duration: 200,
    category: 'Axé & Pop',
    language: 'Portuguese',
  },
  {
    id: '20',
    title: 'Meu Abrigo',
    artist: 'Melim',
    youtubeId: 'xIlc01vo_fg',
    thumbnail: 'https://img.youtube.com/vi/xIlc01vo_fg/maxresdefault.jpg',
    duration: 195,
    category: 'Axé & Pop',
    language: 'Portuguese',
  },
  {
    id: '21',
    title: 'Boate Azul',
    artist: 'Zezé Di Camargo & Luciano',
    youtubeId: 'BfM6lwCbdNE',
    thumbnail: 'https://img.youtube.com/vi/BfM6lwCbdNE/maxresdefault.jpg',
    duration: 270,
    category: 'Sertanejo',
    language: 'Portuguese',
  },
  {
    id: '22',
    title: 'Xote das Meninas',
    artist: 'Luiz Gonzaga',
    youtubeId: 'QpTKdWQEeN4',
    thumbnail: 'https://img.youtube.com/vi/QpTKdWQEeN4/maxresdefault.jpg',
    duration: 185,
    category: 'Forró & Regional',
    language: 'Portuguese',
  },
  {
    id: '23',
    title: 'Anunciação',
    artist: 'Alceu Valença',
    youtubeId: 'MoSGW0vwFgU',
    thumbnail: 'https://img.youtube.com/vi/MoSGW0vwFgU/maxresdefault.jpg',
    duration: 225,
    category: 'Forró & Regional',
    language: 'Portuguese',
  },
  {
    id: '24',
    title: 'Me Dê Motivo',
    artist: 'Tim Maia',
    youtubeId: 'bCkVaRu6kic',
    thumbnail: 'https://img.youtube.com/vi/bCkVaRu6kic/maxresdefault.jpg',
    duration: 250,
    category: 'Soul & Funk',
    language: 'Portuguese',
  },
]

export function searchSongs(query: string): Song[] {
  if (!query.trim()) return songDatabase
  
  const lowerQuery = query.toLowerCase()
  return songDatabase.filter(
    song =>
      song.title.toLowerCase().includes(lowerQuery) ||
      song.artist.toLowerCase().includes(lowerQuery)
  )
}

export function getSongsByCategory(category: string): Song[] {
  return songDatabase.filter(song => song.category === category)
}

export const categories = [
  'Bossa Nova & MPB',
  'Sertanejo',
  'Rock Brasileiro',
  'Samba & Pagode',
  'Forró & Regional',
  'Axé & Pop',
  'Soul & Funk',
]
